---
- name: make the Ansible users to access the machines
  hosts: all
  become: true
  tasks:
          - name: this will remove the users
            ansible.builtin.user:
                    name: ansible
                    state: absent
                    remove: true
          - name: this will make the users
            ansible.builtin.user:
                    name: ansible
                    password: redhat!
                    append: true
                    groups: wheel
                    state: present
