---
- name: register the system
  hosts: all
  become: true
  tasks:
          - name: configure system to sate
            dnf:
                    name: http://{{satellite_fqdn}}/pub/katello-ca-consumer-latest.noarch.rpm
                    state: latest
                    disable_gpg_check: yes
            vars:
                    satellite_fqdn: satellite.example.com
          - name: the task
            redhat_subscription:
                    state: present
                    activationkey: Demo
                    org_id: Default_Organization
          - name: Install katello-agent
            yum:
                    name: katello-agent
                    state: latest
